# Generated by Django 5.1.1 on 2024-11-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="is_read",
        ),
    ]
