# Generated by Django 5.1.1 on 2024-11-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("read", "Read"), ("replied", "Replied")],
                default="new",
                max_length=10,
            ),
        ),
    ]
